baseURL: "https://verdugo-danieml.github.io/AverageAiStudent/"
languageCode: en-us
title: AverageAIStudent
theme: PaperMod

enableEmoji: true

params:
  author: David Hwang
  homeInfoParams:
    Title: "the dev playbook"
    Content: >
      Welcome to the **dev playbook** 🎉
      - This space shares step-by-step guides for devs to building different backend/infra projects 🙂
      - 
      - Tin-can projects that I will be working on include but are not limited to:
      - • API with Swagger 2.0 in Go
      - • Secure Authentication with Refresh Token
      - • Terraform Module that deploys a Lambda + API Gateway
      - • Deployment of CI/CD server like Jenkins to EC2 autoscaling groups
      - • Kubernetes Cluster with Prometheus and Grafana
      - • + many others from different categories
  socialIcons:
    - name: Github
      url: "https://github.com/dhij"
    - name: Youtube
      url: "https://www.youtube.com/@dhij"
    - name: Rss
      url: "index.xml"

  ShowReadingTime: true
  ShowShareButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
